### ISSUE TITLE
architect.js

### ISSUE THREAD

**Issue by hamid67fathi** [Wikitude/wikitude-sdk-samples#10]
Hi
index.html can not  reference to architect.js .
the path is invalid also `<script src="architect://architect.js"></script>` doesn't work either.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @hamid67fathi,
the script include you mentioned does not work on iOS 9+ when your Architect World is loaded from a https url. You need to switch to `<script src="https://www.wikitude.com/libs/architect.js"></script>`. This one does not connect to our server but is handled from the SDK internally.
