### ISSUE TITLE
since 6 TargetCollectionResource is undefined

### ISSUE THREAD

**Issue by elgubenis** [Wikitude/wikitude-sdk-samples#11]
AR.TargetCollectionResource is undefined since the SDK version 6.0, what should i do instead?

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @elgubenis, we newly introduced AR.TargetCollectionResource in our SDK version 6.0.0. It's unavailable in previous version but should be available in 6.0.0.

How did you encounter this problem?

**Comment by elgubenis** [comment]
i was using version 6, and did log AR.TargetCollectionResource and its undefined (cordova JavaScript) i had to downgrade to 5.3 and now use the old way (2DObject etc.)

they were also more "classes" not available, and i saw that they existed in the architect.js which is in t he filesystem, but it felt like some else architect.js was injected in the build, were TargetCollectionResource and a few others were not available, there were 3 "classes" not available, TargetCollectionResource and some others, but i cannot remember sorry.

**Comment by elgubenis** [comment]
i ran my tests on Android 7 and iOS 10

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @elgubenis,
could you give our Android/iOS example app a try? So far I wasn't able to reproduce the problems you have mentioned. Maybe you can send us some (ready for execution)test projects to info@wikitude.com so that I can have a look at it?
