### ISSUE TITLE
requiredFeatures

### ISSUE THREAD

**Issue by shaneparsons** [Wikitude/wikitude-sdk-samples#12]
I'm unable to find a list of what can / should be placed in the `requiredFeatures` array. The only ones I'm aware of are `geo` and `ir`.

**Comment by danielguttenberg** [comment]
Which product are we talking about (JS SDK, Titanium, Xamarin, Cordova)?

**Comment by shaneparsons** [comment]
Cordova mainly. JS SDK would be beneficial too though.

**Comment by AndreasSchacherbauerWikitude** [comment]
(WikitudePlugin.js is the file you're looking for)[https://github.com/Wikitude/wikitude-cordova-plugin/blob/master/www/WikitudePlugin.js#L21] - In short: you can choose from 'geo', 'image_tracking' and (not yet available as a constant) 'instant_tracking'
