### ISSUE TITLE
 http-404 error for architect.js

### ISSUE THREAD

**Issue by dogutumerdem** [Wikitude/wikitude-sdk-samples#23]
Hello,

Trying to run "08_PointOfInterest_1_PoiAtLocation" sample, but getting the http-404 error for architect.js file from url: https://www.wikitude.com/libs/architect.js

[this](http://www.wikitude.com/external/doc/documentation/latest/android/samples.html?_ga=2.205540755.1281175318.1531340125-1789702781.1531340125#including-the-architectjs-library) document says _"The actual file will be injected by the Wikitude SDK on run-time, so don't worry if you see a 404 - Not found in case you try to download the file. Even if it looks like the Wikitude SDK is loading this file remotely, it will only be replaced locally without any network connection opening up."_

is that true ? because I end up with blank page...

where can I find this file ?

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi,
could it be that you try to open the example in a desktop browser? If not, can you please give us more information about which device, OS and SDK version you're using?

Best regards,
Andreas

**Comment by dogutumerdem** [comment]
hi,
I downloaded yesterday. Which SDK should I install ? (Cordova, Unity downloaded but not contains that architect.js as well)
Unity samples worked well and thought everything works well. But when I started the sample with Chrome Browser on windows 10 desktop, it couldn't find the architect.js.

I'm missing something, but I didn't understand...

**Comment by AndreasSchacherbauerWikitude** [comment]
"But when I started the sample with Chrome Browser on windows 10 desktop" that's expected behavior. architect.js is coming from our mobile SDKs (Android/iOS). They intercept the load request for this file and return a response that is bundled within the SDK. 
So of you run the Architect World by loading it with our mobile SDKs on a iOS/Android device, it will work.
