### ISSUE TITLE
How to stop/exit from AR world programmatically from JS code?

### ISSUE THREAD

**Issue by Ravim-addweb** [Wikitude/wikitude-sdk-samples#26]
I have an application developed which uses wikitude React native plugin. I have requirement of internal redirection upon scanning images. Therefore I need to close/stop the AR experience. Can you please tell me how it can be possible? Thanks!

**Comment by Ravim-addweb** [comment]
Any updates yet?

**Comment by pnagele** [comment]
Hi Ravim,

thanks for posting and trying the Wikitude SDK. The React Native plugin is from a 3rd party vendor and not officially supported through Wikitude. You can try at their Github repo https://github.com/brave-digital/react-native-wikitude or in the Wikitude support forums (https://support.wikitude.com/support/home).

All the best with your project.
