### ISSUE TITLE
Urgency crash on iOS JS SDK(5.1.4)

### ISSUE THREAD

**Issue by foobra** [Wikitude/wikitude-sdk-samples#9]
Hi, I've got a very urgency crash on iOS SDK(5.1.4), please have a look and thanks. http://stackoverflow.com/questions/37958677/ios-wikitude-sdk5-4-1-got-crashed-when-lock-the-screen

**Comment by pnagele** [comment]
Please see comment in Stackoverflow

> Please have a look at the newly release Wikitude SDK 5.2.0 - it includes several stability improvements for pause/resume and power on/off cycles. Confident, that this will fix your issue.
